/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PolarNick239 (https://sketchfab.com/PolarNick239)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gerezani-fort-kilwa-kisiwani-tanzania-c253ff6e69074525839e0b9e7ebe05a8
Title: Gerezani fort, Kilwa Kisiwani, Tanzania
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import FortScene from "../assets/3d/fort_1.glb";

export function Fort(props) {
  const { nodes, materials } = useGLTF(FortScene);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.667}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Model_material0_0.geometry}
          material={materials.material0}
          
          rotation={[-Math.PI, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/fort_1.glb");

